import { fmtDate, SEV } from "../api.js";

export default function CitationCard({ contradiction: c, company, onClose }) {
  if (!c) return null;
  const color = SEV[c.severity];
  const stop = (e) => e.stopPropagation();

  const sides = [
    { label: "Statement A", date: c.a_date, source: c.a_source, speaker: c.a_speaker, quote: c.a_quote },
    { label: "Statement B", date: c.b_date, source: c.b_source, speaker: c.b_speaker, quote: c.b_quote },
  ];

  return (
    <>
      <style>{`
        @media print {
          body * { visibility: hidden; }
          #citation-card, #citation-card * { visibility: visible; }
          #citation-card { position: absolute; inset: 0; box-shadow: none !important; }
          .no-print { display: none !important; }
        }
      `}</style>
      <div onClick={onClose} className="no-print" style={{
        position: "fixed", inset: 0, background: "rgba(20,18,14,0.4)", zIndex: 75,
        display: "flex", alignItems: "center", justifyContent: "center", padding: 40,
        animation: "fadeIn 250ms ease both", overflowY: "auto",
      }}>
        <div id="citation-card" onClick={stop} style={{
          background: "#fff", borderRadius: 4, maxWidth: 640, width: "100%",
          padding: "44px 48px", boxShadow: "0 24px 60px rgba(0,0,0,.25)",
          animation: "popIn 320ms cubic-bezier(.2,.8,.2,1) both",
        }}>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 28 }}>
            <div>
              <div style={{ fontFamily: "var(--font-mono)", fontSize: 10, textTransform: "uppercase",
                letterSpacing: ".1em", color: "#8a8478" }}>Counterpoint · Contradiction Record</div>
              <div style={{ fontFamily: "var(--font-serif)", fontSize: 20, color: "#16232e", marginTop: 6 }}>
                {company?.name || company?.ticker} — {c.topic_name}
              </div>
            </div>
            <button onClick={onClose} className="no-print" style={{ border: "none", background: "transparent",
              fontSize: 20, cursor: "pointer", color: "#7a7468", lineHeight: 1 }}>×</button>
          </div>

          <div style={{
            display: "inline-block", padding: "4px 12px", borderRadius: 999,
            background: `color-mix(in oklch, ${color} 15%, #fff)`, color,
            fontFamily: "var(--font-mono)", fontSize: 11, fontWeight: 600, marginBottom: 24,
          }}>{c.severity} severity contradiction</div>

          {sides.map((s) => (
            <div key={s.label} style={{ marginBottom: 20, paddingBottom: 20, borderBottom: "1px solid #e5e0d8" }}>
              <div style={{ fontFamily: "var(--font-mono)", fontSize: 10, color: "#8a8478", marginBottom: 8 }}>
                {s.label} · {fmtDate(s.date)} · {s.source === "synthetic" ? "synthetic demo data" : "real filing"}
              </div>
              <div style={{ fontFamily: "var(--font-serif)", fontSize: 16, lineHeight: 1.6, color: "#16232e",
                marginBottom: 8 }}>&ldquo;{s.quote}&rdquo;</div>
              <div style={{ fontSize: 12, color: "#5a544a" }}>{s.speaker}</div>
            </div>
          ))}

          <div style={{ fontFamily: "var(--font-mono)", fontSize: 10, textTransform: "uppercase",
            letterSpacing: ".08em", color: "#8a8478", marginBottom: 6 }}>Why this is a contradiction</div>
          <div style={{ fontSize: 13.5, lineHeight: 1.6, color: "#3a352c", marginBottom: 28 }}>{c.reasoning}</div>

          <div style={{ fontFamily: "var(--font-mono)", fontSize: 9, color: "#a39d90",
            borderTop: "1px solid #e5e0d8", paddingTop: 14 }}>
            Every quote above is verified verbatim against its source document. Generated by
            Counterpoint on {new Date().toLocaleDateString()}.
          </div>

          <div className="no-print" style={{ marginTop: 24, display: "flex", gap: 10 }}>
            <button onClick={() => window.print()} style={{
              border: "none", borderRadius: 999, padding: "10px 20px", cursor: "pointer",
              background: "var(--accent)", color: "#fff", fontFamily: "var(--font-mono)", fontSize: 12,
            }}>Print / Save as PDF</button>
            <button onClick={onClose} style={{
              border: "1px solid var(--hairline)", borderRadius: 999, padding: "10px 20px", cursor: "pointer",
              background: "transparent", color: "var(--inkSoft)", fontFamily: "var(--font-mono)", fontSize: 12,
            }}>Close</button>
          </div>
        </div>
      </div>
    </>
  );
}
